# Generated by Django 4.2 on 2023-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0003_list_completed_at_list_created_at_list_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='position',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='type',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
