# Generated by Django 4.2 on 2023-10-01 13:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0004_type_completed_at_type_created_at_type_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='type',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witype', to='app_baseline.type'),
        ),
    ]
