# Generated by Django 4.2 on 2023-10-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_baseline', '0008_role_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('done', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_in_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CHILDREN', to='app_baseline.work')),
                ('type', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bltype', to='app_baseline.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_groups', models.ManyToManyField(blank=True, related_name='%(class)s_admin_groups', related_query_name='administered_by_group', to='auth.group')),
                ('admins', models.ManyToManyField(blank=True, related_name='%(class)s_admins', related_query_name='administered_by_user', to=settings.AUTH_USER_MODEL)),
                ('editor_groups', models.ManyToManyField(blank=True, related_name='%(class)s_editor_groups', related_query_name='editable_by_group', to='auth.group')),
                ('editors', models.ManyToManyField(blank=True, related_name='%(class)s_editors', related_query_name='editable_by_user', to=settings.AUTH_USER_MODEL)),
                ('viewer_groups', models.ManyToManyField(blank=True, related_name='%(class)s_viewer_groups', related_query_name='viewable_by_group', to='auth.group')),
                ('viewers', models.ManyToManyField(blank=True, related_name='%(class)s_viewers', related_query_name='viewable_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
