# Generated by Django 4.2 on 2023-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0012_alter_permission_inherit'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
