# Generated by Django 4.2 on 2023-10-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0014_rename_is_public_permission_users_can_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='can_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
