# Generated by Django 4.2 on 2023-10-11 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_baseline', '0016_remove_customgroup_can_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AddField(
            model_name='permission',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='grouppermissions', to='app_baseline.customgroup'),
        ),
        migrations.AddField(
            model_name='permission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='userpermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
