# Generated by Django 4.2 on 2023-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0017_remove_permission_group_remove_permission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
