# Generated by Django 4.2 on 2023-10-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0018_alter_permission_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project1',
        ),
    ]
