# Generated by Django 4.2 on 2023-10-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_baseline', '0019_delete_project1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherit', models.BooleanField(default=False)),
                ('users_can_view', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('list_node', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_baseline.list')),
                ('permission_node', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_baseline.permission')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
