# Generated by Django 4.2 on 2023-10-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0020_listpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
