# Generated by Django 4.2 on 2023-10-15 04:16

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_baseline', '0022_listpermission_active_listpermission_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.AlterField(
            model_name='list',
            name='permission',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authzlistref', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='listpermission',
            name='permission_node',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='work',
            name='permission',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authzworkref', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='GenericPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
