# Generated by Django 4.2 on 2023-10-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0023_remove_permission_groups_remove_permission_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='listpermission',
            name='permission_node',
        ),
    ]
