# Generated by Django 4.2 on 2024-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_rename_bio_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
