# Generated by Django 4.2 on 2024-03-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0009_devvaluestream_opsvaluestream_delete_valuestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='ops_valuestream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_web.opsvaluestream'),
        ),
    ]
