# Generated by Django 4.2 on 2024-03-11 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_web', '0010_devvaluestream_ops_valuestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devvaluestream',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authdev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devvaluestream',
            name='ops_valuestream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devvaluestream', to='app_web.opsvaluestream'),
        ),
        migrations.AlterField(
            model_name='opsvaluestream',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authops', to=settings.AUTH_USER_MODEL),
        ),
    ]
