# Generated by Django 4.2 on 2024-03-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0012_valuestreamsteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='total_delay_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='total_value_creation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='total_delay_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='total_value_creation_time',
            field=models.IntegerField(default=0),
        ),
    ]
