# Generated by Django 4.2 on 2024-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0014_devvaluestream_supported_ops_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsvaluestream',
            name='trigger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opsvaluestream',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
