# Generated by Django 4.2 on 2024-03-12 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0015_alter_opsvaluestream_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsvaluestream',
            name='trigger',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='opsvaluestream',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
