# Generated by Django 4.2 on 2024-03-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0016_alter_opsvaluestream_trigger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsvaluestream',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='opsvaluestream',
            name='value',
        ),
    ]
