# Generated by Django 4.2 on 2024-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0017_remove_opsvaluestream_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devvaluestream',
            name='supported_ops_steps',
            field=models.ManyToManyField(blank=True, related_name='supporting_dev_streams', to='app_web.valuestreamsteps'),
        ),
    ]
