# Generated by Django 4.2 on 2024-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0018_alter_devvaluestream_supported_ops_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsvaluestream',
            name='trigger',
            field=models.CharField(default='Trigger', max_length=255),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='value',
            field=models.CharField(default='Value', max_length=255),
        ),
    ]
