# Generated by Django 4.2 on 2024-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0019_opsvaluestream_trigger_opsvaluestream_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsvaluestream',
            name='trigger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opsvaluestream',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
