# Generated by Django 4.2 on 2024-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0020_alter_opsvaluestream_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuestreamsteps',
            name='delay_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='value_creation_time',
            field=models.IntegerField(default=0),
        ),
    ]
