# Generated by Django 4.2 on 2024-03-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0021_valuestreamsteps_delay_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuestreamsteps',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='valuestreamsteps',
            name='object_id',
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='devvaluestream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_web.devvaluestream'),
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='opsvaluestream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_web.opsvaluestream'),
        ),
    ]
