# Generated by Django 4.2 on 2024-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0023_keyresult_strategictheme_quarterlymeasure_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlymeasure',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
