# Generated by Django 4.2 on 2024-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0025_capability_epic_feature_spike_keyresult_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlymeasure',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='spike',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='strategictheme',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
