# Generated by Django 4.2 on 2024-03-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0026_capability_deleted_epic_deleted_feature_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='dvs_types',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='ovs_types',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='deleted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
