# Generated by Django 4.2 on 2024-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0027_devvaluestream_deleted_dvs_types_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='trigger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
