# Generated by Django 4.2 on 2024-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0028_devvaluestream_trigger_devvaluestream_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
