# Generated by Django 4.2 on 2024-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0029_devvaluestream_owner_opsvaluestream_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devvaluestream',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='opsvaluestream',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
