# Generated by Django 4.2 on 2024-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0030_alter_devvaluestream_name_alter_opsvaluestream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='rolled_ca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='rolled_ca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuestreamsteps',
            name='percentage_accurate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
