# Generated by Django 4.2 on 2024-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0031_devvaluestream_rolled_ca_opsvaluestream_rolled_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuestreamsteps',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
