# Generated by Django 4.2 on 2024-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0034_alter_capability_deleted_alter_epic_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organizations',
            field=models.ManyToManyField(related_name='members', to='app_web.organization'),
        ),
    ]
