# Generated by Django 5.0.3 on 2024-03-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0035_profile_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTransformationCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('docs', models.TextField(blank=True, null=True)),
                ('dev_value_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_transformation_canvases', to='app_web.devvaluestream')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpsTransformationCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('docs', models.TextField(blank=True, null=True)),
                ('ops_value_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_transformation_canvases', to='app_web.opsvaluestream')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
