# Generated by Django 5.0.3 on 2024-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0037_rename_dev_value_stream_devtransformationcanvas_devvaluestream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opstransformationcanvas',
            name='boundaries_and_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opstransformationcanvas',
            name='demand_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opstransformationcanvas',
            name='improvement_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
