# Generated by Django 5.0.3 on 2024-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0038_opstransformationcanvas_boundaries_and_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtransformationcanvas',
            name='boundaries_and_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devtransformationcanvas',
            name='demand_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devtransformationcanvas',
            name='improvement_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
