# Generated by Django 5.0.3 on 2024-03-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0040_devtransformationcanvas_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStateDTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('dtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state_dtc', to='app_web.devtransformationcanvas')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutureStateDTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('dtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_state_dtc', to='app_web.devtransformationcanvas')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
