# Generated by Django 5.0.3 on 2024-03-22 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0042_devtransformationcanvas_marked_rows_with_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='AWProfile',
        ),
    ]
