# Generated by Django 5.0.3 on 2024-03-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0027_alter_project_end_date_alter_project_start_date'),
        ('app_web', '0045_rename_safe_type_organization_org_type_projectadmins'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingWBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_baseline.list')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_web.organization')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_baseline.type')),
            ],
            options={
                'verbose_name': 'WBS Mapping',
                'verbose_name_plural': 'WBS Mappings',
            },
        ),
    ]
