# Generated by Django 5.0.3 on 2024-03-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0047_alter_mappingwbs_list_alter_mappingwbs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingwbs',
            name='type',
        ),
    ]
