# Generated by Django 5.0.3 on 2024-03-27 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0028_typetype_type_type_type'),
        ('app_web', '0049_strategictheme_corresponding_mptt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_capabilities', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epic',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_epics', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_features', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spike',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_spikes', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_tasks', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='corresponding_mptt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_user_stories', to='app_baseline.list'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(choices=[('EN', 'Enabler'), ('BU', 'Business')], default='BU', max_length=2)),
                ('corresponding_mptt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_web_components', to='app_baseline.list')),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app_web.epic')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
