# Generated by Django 5.0.3 on 2024-03-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0050_capability_corresponding_mptt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategictheme',
            name='corresponding_mptt_id',
        ),
    ]
