# Generated by Django 5.0.3 on 2024-03-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0028_typetype_type_type_type'),
        ('app_web', '0052_remove_capability_corresponding_mptt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategictheme',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_strategic_themes', to='app_baseline.list'),
        ),
    ]
