# Generated by Django 5.0.3 on 2024-03-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baseline', '0028_typetype_type_type_type'),
        ('app_web', '0053_strategictheme_corresponding_mptt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_capabilities', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='component',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_components', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='epic',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_epics', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='feature',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_features', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='spike',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_spikes', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='task',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_tasks', to='app_baseline.list'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='corresponding_mptt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_web_user_stories', to='app_baseline.list'),
        ),
    ]
