# Generated by Django 5.0.3 on 2024-03-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0055_alter_strategictheme_corresponding_mptt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spike',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spikes', to='app_web.component'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='app_web.component'),
        ),
    ]
