# Generated by Django 5.0.3 on 2024-03-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0056_spike_parent_component_userstory_parent_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epic',
            old_name='theme',
            new_name='strategictheme',
        ),
        migrations.RenameField(
            model_name='spike',
            old_name='parent_capability',
            new_name='capability',
        ),
        migrations.RenameField(
            model_name='spike',
            old_name='parent_component',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='spike',
            old_name='parent_feature',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_spike',
            new_name='spike',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_story',
            new_name='userstory',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='parent_capability',
            new_name='capability',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='parent_component',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='parent_feature',
            new_name='feature',
        ),
    ]
