# Generated by Django 5.0.3 on 2024-03-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0057_rename_theme_epic_strategictheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capability',
            name='epic',
        ),
        migrations.RemoveField(
            model_name='component',
            name='epic',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='strategictheme',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='epic',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='spike',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='spike',
            name='component',
        ),
        migrations.RemoveField(
            model_name='spike',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='task',
            name='spike',
        ),
        migrations.RemoveField(
            model_name='task',
            name='userstory',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='component',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='feature',
        ),
    ]
